apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-nginx
  labels:
    tier: admin-panel
data:
  config : |
    server {
      listen 80;
      index index.html index.php;
      server_name _ localhost;
      set $DOCUMENT /files/data/public;
      root $DOCUMENT;

    location /admin_panel_laravel_log/ {
      auth_basic "Restricted area";
      auth_basic_user_file auth_pass;
      alias files/data/storage/logs/;
      autoindex on;
    }
 
    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
      access_log off;
      expires max;
      log_not_found off;
    }

    location / {
      # add_header Access-Control-Allow-Origin *;
      try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass admin-panel:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }

