version: '3.7'

services:
  nginx:
    container_name: fitness-back-nginx
    image: nginx:latest
    restart: always
    #depends_on:
    #  - fpm
    ports:
      - "8080:80"
    volumes:
      - './configs/nginx/conf.d/:/etc/nginx/conf.d/:rw'
      - './configs/nginx/nginx.conf:/etc/nginx/nginx.conf:rw'
      - './../:/data:rw'
      - ./_logs:/var/log/nginx
    networks:
          fitness:
            ipv4_address: 172.90.0.1

