apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
  namespace: prod
spec:
  schedule: "0 0 * * *" 
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 20
      ttlSecondsAfterFinished: 20 
      template:
        spec:
          containers:
          - name: backup-container
            image: new
            command: ["/bin/sh", "-c", "cd /app && bash backup.sh"]
          restartPolicy: Never
          imagePullSecrets: 
            - name: cicd

