apiVersion: batch/v1
kind: CronJob
metadata:
  generation: 1
  name: backup-job
  namespace: 
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 20
      backoffLimit: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - cd /app && bash backup.sh
            image: backup:new
            imagePullPolicy: IfNotPresent
            name: backup-container
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 20
  schedule: 0 6 * * 5
  successfulJobsHistoryLimit: 1
  suspend: false
