apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-panel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: admin-panel
